name: 15-minute-cron
on:
  schedule:
    - cron: '5-59/15 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://wettr-service.vercel.app/api/update' \
          --header 'passphrase: ${{secrets.PASSPHRASE}}'
